# Generated by Django 5.2.4 on 2025-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imdb_rating_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_url',
            field=models.URLField(blank=True, help_text='High-quality backdrop image URL from TMDB'),
        ),
    ]
