# Generated by Django 5.2.4 on 2025-08-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_backdrop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='poster',
            field=models.ImageField(blank=True, help_text='Genre poster image', null=True, upload_to='genres/'),
        ),
    ]
