# Generated by Django 5.2.4 on 2025-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='poster',
            field=models.URLField(blank=True, help_text='Genre poster image URL', max_length=500),
        ),
    ]
