# Generated by Django 5.2.5 on 2025-08-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_extend_media_field_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="actors/"),
        ),
        migrations.AlterField(
            model_name="director",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="directors/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
    ]
