# Generated by Django 5.2.5 on 2025-08-07 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_actor_photo_alter_director_photo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_year"], name="movies_movi_release_81d5c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date"], name="movies_movi_release_b7ac7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["imdb_rating"], name="movies_movi_imdb_ra_8e4972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["title"], name="movies_movi_title_652549_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["created_at"], name="movies_movi_created_619207_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_year", "title"], name="movies_movi_release_c866ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date", "title"], name="movies_movi_release_179d63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["imdb_rating", "title"], name="movies_movi_imdb_ra_0d3d49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(
                fields=["user", "added_at"], name="movies_watc_user_id_9f3949_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(
                fields=["movie", "added_at"], name="movies_watc_movie_i_2cfe53_idx"
            ),
        ),
    ]
